import { Inject, Injectable, ConflictException } from '@nestjs/common';
import { CustomerRepositoryPort } from '../../domain/ports/customer.repository.port';
import { Customer } from '../../domain/models/customer.entity';
import { CreateCustomerDto } from '../dtos/create-customer.dto';
import { SharedMessages } from '@app/shared';

@Injectable()
export class CreateCustomerUseCase {
  constructor(
    @Inject('CustomerRepositoryPort')
    private readonly customerRepository: CustomerRepositoryPort,
  ) {}

  async execute(dto: CreateCustomerDto): Promise<Customer> {
    const exists = await this.customerRepository.findByDocument(dto.document);
    if (exists) {
      throw new ConflictException(
        SharedMessages.Customer.ALREADY_REGISTERED,
      );
    }

    const newCustomer = new Customer(
      '', // ID is generated by MongoDB
      dto.name,
      dto.lastName,
      dto.document,
      dto.email,
      dto.phone,
    );

    return await this.customerRepository.save(newCustomer);
  }
}
