version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: bcs_api_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: bcs_api_redis
    ports:
      - "6379:6379"

  api-gateway:
    build:
      context: .
      args:
        APP_NAME: api-gateway
    container_name: bcs_api_gateway_service
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    env_file:
      - .env

  applications-service:
    build:
      context: .
      args:
        APP_NAME: applications
    container_name: bcs_api_applications_service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    env_file:
      - .env

  auth-service:
    build:
      context: .
      args:
        APP_NAME: auth
    container_name: bcs_api_auth_service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    env_file:
      - .env

  technical-test-service:
    build:
      context: .
      args:
        APP_NAME: technical-test
    container_name: bcs_api_technical_test_service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    env_file:
      - .env

  customer-service:
    build:
      context: .
      args:
        APP_NAME: customer
    container_name: bcs_api_customer_service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    env_file:
      - .env

volumes:
  mongo_data:
