### AUTENTICACIÓN - SERVICE.HTTP (LOCAL)
### Estas peticiones pasan por el API Gateway (puerto 3000) y se enrutan al microservicio de Auth por Redis.

@host = http://localhost:3000/api/v1
@contentType = application/json

### 1. Iniciar sesión (Admin)
# @name login
POST {{host}}/auth/login
Content-Type: {{contentType}}

{
  "email": "admin@banco.com",
  "password": "Password123!"
}

### 2. Registrar usuario (Admin)
POST {{host}}/auth/register
Content-Type: {{contentType}}

{
  "email": "nuevo.admin@banco.com",
  "password": "Password123!",
  "firstName": "Juan",
  "lastName": "Perez"
}
